import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Swiper } from '@/components/Swiper/container'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="card" />

        <Swiper>
          <swiper-slide>
            <div className="card">
              <strong>1</strong>
            </div>
          </swiper-slide>

          <swiper-slide>
            <div className="card">
              <strong>2</strong>
            </div>
          </swiper-slide>
        </Swiper>
      </main>
    </>
  )
}
